--Criando uma Tabela a Partir de uma Consulta:
CREATE TABLE MELHORES_ARTIGOS AS
SELECT *
FROM  ARTIGO
WHERE NOTA>=9 ;

-- ADICIONAR O CAMPO E-MAIL NA TABELA PESQUISADOR 
ALTER TABLE PESQUISADOR
ADD  EMAIL VARCHAR(40);

-- MODIFICAR O CAMPO E-MAIL NA TABELA PESQUISADOR 
ALTER TABLE PESQUISADOR
MODIFY EMAIL (OU ALTER COLUMN) CHAR(50);

-- ELIMINAR O CAMPO E-MAIL NA TABELA PESQUISADOR
ALTER TABLE PESQUISADOR
DROP COLUMN EMAIL;

-- ADICIONAR UMA RESTRIÇÃO NA TABELA PESQUISADOR
ALTER TABLE PESQUISADOR
ADD CONSTRAINT AK_PESQ_EMAIL UNIQUE (EMAIL);


-- EXCLUINDO UMA TABELA
DROP TABLE MELHORES_ARTIGOS CASCADE CONSTRAINTS;


-- LIMPANDO/TRUNCANDO OS DADOS DE UMA TABELA
TRUNCATE TABLE MELHORES_ARTIGOS; 


--CRIANDO INDICE
CREATE INDEX idx_usu_nome on PESQUISADOR (nome);
CREATE UNIQUE INDEX idx_usu_CPF on PESQUISADOR (CPF);

--EXCLUINDO  INDICE
DROP INDEX idx_usu_nome;

--CRIANDO SEQUENCIAS
CREATE SEQUENCE Contar1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ContarNegativo1 
START WITH 0 
INCREMENT BY -1;

--EXCLUINDO UMA SEQUENCIA
DROP SEQUENCE ContarNegativo1;

--CRIANDO UMA VISAO
CREATE VIEW MELHORES_ARTIGOS_PT AS
SELECT *
FROM  ARTIGO
WHERE NOTA>=9  AND IDIOMA = ‘PORTUGUES’;

--EXCLUINDO UMA VISAO
DROP VIEW MELHORES_ARTIGOS_PT;


--CONSULTA 1 - PROJETAR TODAS AS INFORMAÇÕES DOS PESQUISADORES
SELECT *
FROM PESQUISADOR ;


-- CONSULTA 2 - PROJETAR A MÉDIA DAS NOTAS DOS ARTIGOS
SELECT TRUNC(AVG (NOTA), 2)
FROM ARTIGO;


/* CONSULTA 3 - PROJETAR TODOS OS ARTIGOS(TÍTULOS) E SUAS NOTAS COM -1 PONTO */
SELECT TITULO, NOTA - 1
FROM ARTIGO;


/* CONSULTA 4 - PROJETAR A QUANTIDADE DE PESQUISADORES CADASTRADOS*/
SELECT COUNT (*) AS QUANTIDADE, 'UD' AS UNIDADE
FROM PESQUISADOR


-- CONSULTA 5 - PROJETAR TODOS OS IDIOMAS DOS ARTIGOS
SELECT ALL IDIOMA -- ou SELECT IDIOMA		
FROM ARTIGO


/* CONSULTA 6 - PROJETAR TODOS OS IDIOMAS, SEM DUPLICATAS, DOS ARTIGOS */
SELECT DISTINCT IDIOMA
FROM ARTIGO;

/* CONSULTA 7 -  PROJETAR TODOS OS NOMES E INSTITUIÇÕES DA TABELA PESQUISADOR */
SELECT P.NOME, P.INSTITUICAO
FROM PESQUISADOR P;


/* CONSULTA 8 - PROJETAR TODOS OS TÍTULOS DOS ARTIGOS E SUAS NOTAS COM –1 PONTO */
SELECT TITULO, NOTA - 1 AS REDUCAO
FROM ARTIGO;

--CONSULTA 9 - PROJETAR ARTIGOS COM NOTA ACIMA DE 8
SELECT *
FROM ARTIGO
WHERE NOTA > 8;


/* CONSULTA 11 - PROJETAR OS EVENTOS QUE OCORRERAM EM 2010, 2012 OU 2014 */
SELECT *
FROM  EVENTO
WHERE ANO IN (2019, 2021, 2022);


/* CONSULTA 12 - PROJETAR TODOS OS PESQUISADORES CUJO NOME TENHA 10 CARACTERES E INICIE COM R */
SELECT *
FROM PESQUISADOR
WHERE NOME LIKE 'R___';

/*CONSULTA 13 - PROJETAR TODOS OS ARTIGOS QUE TENHAM BANCO DE DADOS NO SEU TÍTULO */
SELECT *
FROM ARTIGO
WHERE TITULO LIKE '%DATABASE%';


/*CONSULTA 14 - PROJETAR TODOS OS ARTIGOS AINDA NÃO PUBLICADOS EM EVENTOS */
SELECT *
FROM ARTIGO
WHERE COD IS NULL;

/* CONSULTA 15 - PROJETAR TODOS OS ARTIGOS QUE INICIAM COM ‘DA’, ESTÃO COM NOTA DEFINIDA E FORAM ESCRITOS EM PORTUGUÊS OU INGLÊS*/
SELECT *
FROM ARTIGO
WHERE TITULO LIKE 'DA%' 
AND NOTA IS NOT NULL  
AND (IDIOMA = 'PORTUGUES' OR IDIOMA = 'INGLES');

/* CONSULTA 16 - PROJETAR , EM LETRAS MINÚSCULAS, OS NOMES E, EM LETRAS MAIÚSCULAS, AS INSTITUIÇÕES DA TABELA PESQUISADOR*/
SELECT LOWER(P.NOME), UPPER (P.INSTITUICAO)
FROM PESQUISADOR P;


/* CONSULTA 17 - PROJETAR A CONCATENAÇÃO DE DUAS STRINGS E MOSTRÁ-LAS EM MAIÚSCULO */
SELECT 'Hello World' ORIGINAL, UPPER(CONCAT('Hello World', 'Teste') ) MODIFICADO
FROM DUAL;


-- CONSULTA 18 - PROJETAR A SOMA DE UM NÚMERO E UMA STRING
SELECT 100+TO_NUMBER('100') 
FROM DUAL;


-- CONSULTA 19 - PROJETAR A DATA DO SISTEMA
SELECT SYSDATE 
FROM DUAL;

-- CONSULTA 20 - PROJETAR O DIA, MÊS E ANO DE DATA DO SISTEMA
SELECT EXTRACT(DAY FROM sysdate), EXTRACT(MONTH FROM sysdate), EXTRACT(YEAR FROM sysdate) FROM DUAL; 
--OU
SELECT TO_CHAR (sysdate, 'dd'), TO_CHAR (sysdate, 'MM'), TO_CHAR (sysdate, 'YY') FROM DUAL;


/* CONSULTA 21 - PROJETAR O TÍTULO DE TODOS OS ARTIGOS JOIN” PUBLICADOS E A SIGLA DE SEUS RESPECTIVOS EVENTOS  
SEM USAR “INNER  */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A, EVENTO E
WHERE  A.COD = E.COD;

/* CONSULTA 22 - PROJETAR O TÍTULO DE TODOS OS ARTIGOS PUBLICADOS E A SIGLA DOS SEUS RESPECTIVOS EVENTOS  - 
USANDO “INNER JOIN” */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E.COD);

/* CONSULTA 23 - PROJETAR OS NOMES DE TODOS OS PESQUISADORES E OS TÍTULOS DE SEUS RESPECTIVOS 
ARTIGOS PUBLICADOS NOS IDIOMAS PORTUGUÊS OU INGLÊS  - SEM USAR “INNER JOIN” */
SELECT P.NOME, A.TITULO
FROM PESQUISADOR P, ESCREVE E, ARTIGO A
WHERE P.CPF =  E.CPF AND 
      E.MAT =  A.MAT AND 
      A.IDIOMA IN ('PORTUGUÊS','INGLÊS') ;

/* CONSULTA 24 - PROJETAR OS NOMES DE TODOS OS PESQUISADORES E OS 
TÍTULOS DOS SEUS RESPECTIVOS ARTIGOS PUBLICADOS NOS IDIOMAS PORTUGUÊS OU INGLÊS  
- USANDO “INNER JOIN” */
SELECT P.NOME, A.TITULO
FROM PESQUISADOR P INNER JOIN ESCREVE E ON (P.CPF = E.CPF) 
     INNER JOIN ARTIGO A ON (E.MAT = A.MAT)
WHERE A.IDIOMA IN ('PORTUGUES','INGLES') ;


/* CONSULTA 25 - PROJETAR TODOS OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS) QUANDO PUBLICADOS*/
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A LEFT OUTER JOIN EVENTO E ON (A.COD = E.COD);


/* CONSULTA 26 - PROJETAR TODOS OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS) QUANDO PUBLICADOS*/
SELECT A.TITULO, E.SIGLA
FROM EVENTO E RIGHT OUTER JOIN ARTIGO A ON (A.COD = E.COD);


/* CONSULTA 27 - PROJETAR OS ARTIGOS (TÍTULOS) E SEUS RESPECTIVOS EVENTOS (SIGLAS), 
INCLUINDO OS ARTIGOS NÃO PUBLICADOS E OS EVENTOS SEM ARTIGOS */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A FULL OUTER JOIN EVENTO E ON (A.COD = E.COD);


/* CONSULTA 28  - PROJETAR OS EVENTO (SIGLAS) SEM ARTIGOS PUBLICADOS (NULL PARA TÍTULO DO ARTIGO) 
– USANDO “LEFT OUTER JOIN” */
SELECT E.SIGLA, A.TITULO
FROM EVENTO E LEFT OUTER JOIN ARTIGO A ON (E.COD = A.COD)
WHERE A.COD IS NULL;

/* CONSULTA 29  - PROJETAR OS EVENTO (SIGLAS) SEM ARTIGOS PUBLICADOS (NULL PARA TÍTULO DO ARTIGO) 
- USANDO “RIGTH OUTER JOIN” */
SELECT E.SIGLA, A.TITULO
FROM ARTIGO A RIGHT OUTER JOIN EVENTO E ON (E.COD = A.COD)
WHERE A.COD IS NULL;

/* CONSULTA 30  - PROJETAR OS ARTIGOS (TÍTULOS) NÃO PUBLICADOS E OS EVENTOS (SIGLAS) SEM ARTIGOS 
- USANDO “FULL OUTER JOIN” */
SELECT A.TITULO, E.SIGLA
FROM ARTIGO A FULL OUTER JOIN EVENTO E ON (A.COD = E.COD)
WHERE  A.COD IS NULL OR E.COD IS NULL;


/* CONSULTA 31  - PARA CADA PESQUISADOR, PROJETAR SEU NOME E 
OS NOMES DOS PESQUISADORES MAIS NOVOS DO QUE ELE */
SELECT P1.NOME, P2.NOME
FROM PESQUISADOR P1 INNER JOIN PESQUISADOR P2 ON (P1.NASCIMENTO < P2.NASCIMENTO);


/* CONSULTA 32 - PROJETAR O NOME E O NASCIMENTO DOS PESQUISADORES EM 
ORDEM DECRESCENTE DO NASCIMENTO. PARA DATAS IGUAIS, 
CONSIDERAR A ORDEM ALFABÉTICA DO NOME DO PESQUISADOR */
SELECT NOME, NASCIMENTO
FROM PESQUISADOR
ORDER BY NASCIMENTO DESC, NOME ASC;


-- CONSULTA 33 - PROJETAR A MÉDIA DAS NOTAS DOS ARTIGOS POR EVENTO
SELECT E.SIGLA, AVG (A.NOTA) AS MEDIA_NOTA
FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E. COD)
GROUP BY E.SIGLA;


/* CONSULTA 34 - PROJETAR AS SIGLAS DOS EVENTOS CUJAS MÉDIAS DAS NOTAS DOS ARTIGOS SÃO MAIORES DO QUE 8 */
SELECT E.SIGLA, AVG (A.NOTA) 
FROM EVENTO E INNER JOIN ARTIGO A  ON (E.COD = A. COD)
GROUP BY E.SIGLA 
HAVING AVG (A.NOTA) > 8;


/* CONSULTA 35 - PROJETAR OS NOMES DOS PESQUISADORES QUE PUBLICARAM MAIS DE 3 ARTIGOS */
SELECT P.NOME, COUNT(*) 
FROM PESQUISADOR P INNER JOIN ESCREVE E ON (P.CPF = E.CPF) 
GROUP BY P.NOME
HAVING COUNT(*) > 3;


/* CONSULTA 36 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA ACIMA DA MÉDIA */
SELECT TITULO
FROM ARTIGO
WHERE NOTA > 
            (SELECT AVG (NOTA)
            FROM ARTIGO) ;


/* CONSULTA 37 - PROJETAR OS NOMES DOS PESQUISADORES QUE POSSUEM ARTIGOS SEM NOTA - USANDO “IN” E “INNER JOIN”) */
SELECT NOME
FROM PESQUISADOR 
WHERE CPF NOT IN
                (SELECT CPF
                FROM ESCREVE E INNER JOIN ARTIGO A ON E.MAT =  A.MAT
                WHERE NOTA IS NOT NULL);


/* CONSULTA 38 - PROJETAR OS NOMES DOS PESQUISADORES QUE NASCERAM NO MESMO ANO E TRABALHAM NA MESMA INSTITUIÇÃO DO PESQUISADOR '1111' */
SELECT NOME
FROM PESQUISADOR 
WHERE (INSTITUICAO,TO_CHAR(NASCIMENTO,'YY')) = (SELECT INSTITUICAO,TO_CHAR(NASCIMENTO,'YY')
		    FROM PESQUISADOR
		    WHERE CPF = '1111');

            
/* CONSULTA 39 - POR INSTITUIÇÃO, PROJETAR O NOME E A INSTITUIÇÃO DOS PESQUISADORES MAIS VELHOS */
SELECT NOME, INSTITUICAO
FROM PESQUISADOR
WHERE (INSTITUICAO, TO_CHAR(NASCIMENTO,'YY')) IN 
     (SELECT INSTITUICAO, MIN(TO_CHAR(NASCIMENTO,'YY'))
      FROM PESQUISADOR
      GROUP BY INSTITUICAO)
ORDER BY INSTITUICAO;


/* CONSULTA 40 - PROJETAR OS NOMES DOS PESQUISADORES QUE POSSUEM ARTIGOS 
NÃO PUBLICADO - USANDO “= ANY”, pois é equivalente ao “IN”) */
SELECT NOME
FROM PESQUISADOR 
WHERE CPF = ANY
        (SELECT CPF
        FROM ESCREVE E INNER JOIN ARTIGO A ON (E.MAT = A.MAT)
        WHERE COD IS NULL);


/* CONSULTA 41 - PROJETAR OS NOMES DOS PESQUISADORES,  EXCETO O DO MAIS VELHO */
SELECT NOME
FROM PESQUISADOR
WHERE NASCIMENTO > ANY 
      (SELECT NASCIMENTO
      FROM PESQUISADOR);


/* CONSULTA 42 - PROJETAR OS NOMES DOS PESQUISADORES,  EXCETO O DO MAIS IDOSO */
SELECT NOME
FROM PESQUISADOR
WHERE NASCIMENTO <>
      (SELECT MIN(NASCIMENTO)
       FROM PESQUISADOR)


/* CONSULTA 43 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA MAIOR DO QUE TODOS OS ARTIGOS DO EVENTO ‘SBBD’ */
SELECT TITULO
FROM ARTIGO
WHERE NOTA > ALL
    (SELECT NOTA
    FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E.COD)
    WHERE  E.SIGLA = 'SBBD21');


/* CONSULTA 44 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA MAIOR DO QUE TODOS OS ARTIGOS DO EVENTO ‘SBBD21’ */
SELECT TITULO
FROM ARTIGO
WHERE NOTA >
    (SELECT MAX(NOTA)
    FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E.COD)
    WHERE E.SIGLA = 'SBBD21');


/* CONSULTA 45 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA ACIMA DA MÉDIA GERAL, MOSTRANDO QUANTO A NOTA ESTÁ ACIMA DA MÉDIA */
SELECT TITULO, NOTA - (SELECT AVG(A.NOTA) FROM ARTIGO A)
FROM ARTIGO
WHERE NOTA >
    ( SELECT AVG(A.NOTA)
	FROM ARTIGO A);


/* CONSULTA 46 - PROJETAR O PERCENTUAL DE PESQUISADORES POR INSTITUIÇÃO */
SELECT INSTITUICAO, (QTD/(SELECT COUNT(*) FROM PESQUISADOR))*100 AS "%"
FROM 
	(SELECT INSTITUICAO, COUNT(*) AS QTD
	FROM PESQUISADOR
	GROUP BY INSTITUICAO);


/* CONSULTA 47 - PROJETAR QUAIS SÃO AS INSTITUIÇÕES QUE TÊM MAIS PESQUISADORES DO QUE A MÉDIA */
SELECT INSTITUICAO, COUNT(*)
FROM PESQUISADOR
GROUP BY INSTITUICAO
HAVING COUNT(*) > 
            ( SELECT AVG(QTD)
	        FROM (SELECT INSTITUICAO, COUNT (*) AS QTD 
	             FROM PESQUISADOR
	             GROUP BY INSTITUICAO));


/* CONSULTA 48 - PROJETAR AS SIGLAS DOS EVENTOS COM ARTIGOS PUBLICADOS */
SELECT E.SIGLA
FROM ARTIGO A INNER JOIN EVENTO E ON (A.COD = E.COD);


/* CONSULTA 49 - PROJETAR AS SIGLAS DOS EVENTOS COM ARTIGOS PUBLICADOS – USANDO “EXISTS” */
SELECT E.SIGLA
FROM EVENTO E
WHERE  EXISTS 
        (SELECT * 
        FROM ARTIGO A 
        WHERE A.COD = E.COD);


/* CONSULTA 50 - PROJETAR AS SIGLAS DOS EVENTOS COM ARTIGOS PUBLICADOS – USANDO “IN” */
SELECT E.SIGLA
FROM EVENTO E
WHERE  E. COD IN
               (SELECT A.COD  
                FROM ARTIGO A 
                WHERE A.COD IS NOT NULL);


/* CONSULTA 51 - PROJETAR OS TÍTULOS DOS ARTIGOS COM NOTA ABAIXO DA MÉDIA DOS ARTIGOS PUBLICADOS NO MESMO EVENTO*/
SELECT A1.TITULO
FROM ARTIGO A1
WHERE A1.NOTA <  
            ( SELECT AVG(NOTA)
	        FROM ARTIGO A2 
	        WHERE A1.COD = A2.COD);


/* CONSULTA 52 - PROJETAR AS SIGLAS DOS EVENTOS SEM ARTIGOS PUBLICADOS – USANDO “NOT EXISTS” */
SELECT E.SIGLA
FROM EVENTO E
WHERE  NOT EXISTS 
               (SELECT * 
                FROM ARTIGO A 
                WHERE A.COD = E.COD);


/* CONSULTA 53 - PROJETAR AS SIGLAS DOS EVENTOS SEM ARTIGOS PUBLICADOS – USANDO “NOT IN” */
SELECT E.SIGLA
FROM EVENTO E
WHERE E.COD  NOT IN
               (SELECT A.COD 
                FROM ARTIGO A 
                WHERE A.COD IS NOT NULL);


-- CONSULTA 54 - PROJETAR A QUALIDADE DO ARTIGO 
SELECT TITULO,
CASE 
    WHEN NOTA >= 8 THEN 'BOM'
    WHEN NOTA >= 6 THEN 'REGULAR'
    ELSE 'RUIM'
END AS QUALIDADE
FROM ARTIGO

------------------------------------------



1. Como criar uma tabela a partir de uma consulta?
2. Como adicionar o campo e-mail na tabela PESQUISADOR?
3. Como modificar o campo e-mail na tabela PESQUISADOR?
4. Como eliminar o campo e-mail da tabela PESQUISADOR?
5. Como adicionar uma restrição de unicidade (UNIQUE) ao campo e-mail da tabela PESQUISADOR?
6. Como excluir uma tabela e suas restrições?
7. Como limpar/truncar os dados de uma tabela?
8. Como criar índices em uma tabela?
9. Como excluir um índice?
10. Como criar uma sequência que conta progressivamente ou regressivamente?
11. Como excluir uma sequência?
12. Como criar uma visão com filtro por nota e idioma?
13. Como excluir uma visão?
14. Como projetar todas as informações dos pesquisadores?
15. Como projetar a média das notas dos artigos?
16. Como projetar todos os títulos dos artigos com nota reduzida em 1 ponto?
17. Como contar a quantidade de pesquisadores cadastrados?
18. Como projetar todos os idiomas dos artigos?
19. Como projetar apenas os idiomas distintos dos artigos?
20. Como projetar nome e instituição de cada pesquisador?
21. Como projetar todos os títulos dos artigos com nota -1 e mostrar como “redução”?
22. Como projetar os artigos com nota acima de 8?
23. Como projetar os eventos ocorridos em 2010, 2012 ou 2014?
24. Como projetar pesquisadores com nome de 10 caracteres iniciando com "R"?
25. Como projetar artigos com a palavra “DATABASE” no título?
26. Como projetar artigos que ainda não foram publicados?
27. Como projetar artigos que começam com "DA", têm nota e foram escritos em português ou inglês?
28. Como projetar nomes dos pesquisadores em minúsculo e instituições em maiúsculo?
29. Como concatenar duas strings e exibi-las em maiúsculo?
30. Como somar um número com uma string numérica?
31. Como projetar a data atual do sistema?
32. Como projetar o dia, mês e ano da data atual?
33. Como projetar título de artigos publicados e a sigla de seus eventos sem usar INNER JOIN?
34. Como projetar título de artigos publicados e a sigla de seus eventos usando INNER JOIN?
35. Como projetar nomes dos pesquisadores e seus artigos publicados em português ou inglês sem usar INNER JOIN?
36. Como fazer isso usando INNER JOIN?
37. Como projetar artigos e eventos, incluindo os artigos não publicados e eventos sem artigos (LEFT JOIN)?
38. Como fazer o mesmo com RIGHT JOIN?
39. Como fazer isso com FULL OUTER JOIN?
40. Como projetar eventos sem artigos (com LEFT JOIN)?
41. Como fazer o mesmo com RIGHT JOIN?
42. Como projetar artigos não publicados e eventos sem artigos com FULL OUTER JOIN?
43. Como projetar para cada pesquisador os nomes dos mais novos do que ele?
44. Como projetar nome e nascimento de pesquisadores em ordem decrescente de nascimento e, em caso de empate, por nome?
45. Como projetar a média das notas dos artigos por evento?
46. Como projetar as siglas dos eventos com média de nota maior que 8?
47. Como projetar nomes dos pesquisadores que publicaram mais de 3 artigos?
48. Como projetar títulos de artigos com nota acima da média?
49. Como projetar nomes de pesquisadores que possuem artigos sem nota?
50. Como projetar nomes dos pesquisadores que nasceram no mesmo ano e trabalham na mesma instituição que o pesquisador de CPF '1111'?
51. Como projetar, por instituição, o nome dos pesquisadores mais velhos?
52. Como projetar nomes dos pesquisadores que possuem artigos não publicados usando `= ANY`?
53. Como projetar nomes dos pesquisadores, exceto o mais velho?
54. Como fazer o mesmo excluindo o mais idoso?
55. Como projetar títulos de artigos com nota maior do que todos os artigos do evento 'SBBD'?
56. Como fazer isso projetando nota maior que a maior nota do evento 'SBBD21'?
57. Como projetar quanto a nota de cada artigo está acima da média?
58. Como projetar o percentual de pesquisadores por instituição?
59. Como projetar instituições com mais pesquisadores do que a média?
60. Como projetar siglas de eventos com artigos publicados?
61. Como fazer isso usando `EXISTS`?
62. Como fazer isso usando `IN`?
63. Como projetar títulos de artigos com nota abaixo da média do próprio evento?
64. Como projetar siglas de eventos **sem** artigos publicados usando `NOT EXISTS`?
65. Como fazer o mesmo com `NOT IN`?
66. Como projetar a qualidade do artigo com base na nota (BOM, REGULAR, RUIM)?

---

Se quiser, posso exportar esse conteúdo em PDF ou Word pra você estudar ou imprimir. Deseja isso?
