-- SELECT *
-- FROM PESQUISADOR P
-- WHERE P.CPF = (
--     SELECT CPF FROM ESCREVE) 
-- ;

-- SELECT *
-- FROM ESCREVE;     
-- -------------------------------------

-- SELECT * FROM PESQUISADOR
-- NATURAL JOIN ESCREVE;


-- SELECT TITULO
-- FROM ARTIGO 
-- WHERE NOTA > 
--     (SELECT AVG(NOTA) FROM ARTIGO

-- );

-- SELECT *
-- FROM ARTIGO
-- INNER JOIN EVENTO 
-- ON ARTIGO.COD = EVENTO.COD;


-- SELECT SIGLA, ROUND(AVG(NOTA), 2) AS MEDIA
-- FROM EVENTO
-- JOIN ARTIGO
-- ON ARTIGO.COD = EVENTO.COD
-- GROUP BY NOTA
-- HAVING NOTA > 8;



-- SELECT *
-- FROM ARTIGO;

-- Q3
-- SELECT SIGLA, AVG(A.NOTA) AS MEDIA
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.SIGLA
-- HAVING AVG(NOTA) > 8;

--Q4
-- SELECT INSTITUICAO
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO
-- HAVING COUNT(INSTITUICAO) > 2;
-----------------------------------------------
-- Q1 NOVO GPT
-- SELECT INSTITUICAO, COUNT(NOME) AS QTD
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO;

--Q2 NOVO GPT
-- SELECT INSTITUICAO, COUNT(NOME) AS QTD
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO
-- HAVING COUNT(*) > 2;

--Q3 NOVO GPT
-- SELECT IDIOMA, AVG(NOTA) AS MEDIA
-- FROM ARTIGO
-- GROUP BY IDIOMA;

--Q4 NOVO GPT
-- SELECT IDIOMA, ROUND(AVG(NOTA), 2) AS MEDIA
-- FROM ARTIGO
-- GROUP BY IDIOMA
-- HAVING AVG(NOTA) >= 8;

--Q5 NOVO GPT
-- SELECT E.NOME, E.COD, COUNT(A.COD) AS QTD
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.COD;

--Q6 NOVO GPT
-- SELECT E.NOME, E.COD, COUNT(A.COD) AS QTD
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.COD
-- HAVING COUNT(A.COD) > 2;

--Q7 NOVO GPT


--Q8 NOVO GPT


--Q9 NOVO GPT


--Q10 NOVO GPT
