-- SELECT *
-- FROM PESQUISADOR P
-- WHERE P.CPF = (
--     SELECT CPF FROM ESCREVE) 
-- ;

-- SELECT *
-- FROM ESCREVE;     
-- -------------------------------------

-- SELECT * FROM PESQUISADOR
-- NATURAL JOIN ESCREVE;


-- SELECT TITULO
-- FROM ARTIGO 
-- WHERE NOTA > 
--     (SELECT AVG(NOTA) FROM ARTIGO

-- );

-- SELECT *
-- FROM ARTIGO
-- INNER JOIN EVENTO 
-- ON ARTIGO.COD = EVENTO.COD;


-- SELECT SIGLA, ROUND(AVG(NOTA), 2) AS MEDIA
-- FROM EVENTO
-- JOIN ARTIGO
-- ON ARTIGO.COD = EVENTO.COD
-- GROUP BY NOTA
-- HAVING NOTA > 8;



-- SELECT *
-- FROM ARTIGO;

-- Q3
-- SELECT SIGLA, AVG(A.NOTA) AS MEDIA
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.SIGLA
-- HAVING AVG(NOTA) > 8;

--Q4
-- SELECT INSTITUICAO
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO
-- HAVING COUNT(INSTITUICAO) > 2;
-----------------------------------------------
-- Q1 NOVO GPT
-- SELECT INSTITUICAO, COUNT(NOME) AS QTD
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO;

--Q2 NOVO GPT
-- SELECT INSTITUICAO, COUNT(NOME) AS QTD
-- FROM PESQUISADOR
-- GROUP BY INSTITUICAO
-- HAVING COUNT(*) > 2;

--Q3 NOVO GPT
-- SELECT IDIOMA, AVG(NOTA) AS MEDIA
-- FROM ARTIGO
-- GROUP BY IDIOMA;

--Q4 NOVO GPT
-- SELECT IDIOMA, ROUND(AVG(NOTA), 2) AS MEDIA
-- FROM ARTIGO
-- GROUP BY IDIOMA
-- HAVING AVG(NOTA) >= 8;

--Q5 NOVO GPT
-- SELECT E.SIGLA, E.COD, COUNT(A.COD) AS QTD
-- FROM EVENTO E
-- JOIN ARTIGO A ON E.COD = A.COD
-- GROUP BY E.SIGLA, E.COD;

--Q6 NOVO GPT
-- SELECT E.SIGLA, E.COD, COUNT(A.COD) AS QTD
-- FROM EVENTO E
-- JOIN ARTIGO A ON E.COD = A.COD
-- GROUP BY E.SIGLA, E.COD
-- HAVING COUNT(A.COD) > 2;

--Q7 NOVO GPT
-- SELECT P.CPF, P.NOME, COUNT(MAT) AS QTD
-- FROM PESQUISADOR P
-- JOIN ESCREVE E
-- ON P.CPF = E.CPF
-- GROUP BY P.NOME
-- HAVING COUNT(E.MAT) > 0
-- ORDER BY COUNT(MAT) DESC; 

--Q8 NOVO GPT
-- SELECT A.MAT, P.CPF, P.NOME, AVG(NOTA) AS MEDIA
-- FROM PESQUISADOR P
-- JOIN ESCREVE E
-- ON P.CPF = E.CPF
-- JOIN ARTIGO A
-- ON E.MAT = A.MAT
-- GROUP BY P.NOME
-- HAVING AVG(NOTA) > 8;

--Q9 NOVO GPT
-- SELECT E.COD, MAX(A.NOTA) AS 'NOTA MAX'
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.COD;

--Q10 NOVO GPT
-- SELECT E.COD, MAX(A.NOTA) AS 'NOTA MAX'
-- FROM EVENTO E
-- JOIN ARTIGO A
-- ON E.COD = A.COD
-- GROUP BY E.COD
-- HAVING MAX(A.NOTA) = 10;
--------------------------------------------------------

--Q1
-- SELECT *
-- FROM ARTIGO A
-- WHERE A.NOTA > 8;
--Q2
-- SELECT NOME
-- FROM PESQUISADOR
-- WHERE NOME LIKE 'R%'; 
--Q3

--Q4
-- SELECT *
-- FROM EVENTO
-- WHERE ANO IN (2021, 2022,2023);

--Q5
-- SELECT *
-- FROM ARTIGO
-- WHERE COD IS NULL;

--Q6

--Q7
-- SELECT *
-- FROM ARTIGO
-- WHERE NOTA IS NOT NULL;

--Q8
-- SELECT TITULO, IDIOMA
-- FROM ARTIGO
-- WHERE IDIOMA IN ('PORTUGUES', 'INGLES');
--Q9
-- SELECT *
-- FROM PESQUISADOR
-- WHERE NOME LIKE '___';
--Q10
-- SELECT *
-- FROM ARTIGO
-- WHERE TITULO LIKE 'DA%'
-- AND NOTA IS NOT NULL
-- AND IDIOMA IN ('PORTUGUES', 'INGLES');

--------------------------------------------------------

--Q1
--Q2
--Q3
--Q4
--Q5
--Q6
--Q7
--Q8
--Q9
--Q10